### PR TITLE
Add support for Frosting

### LINKED ISSUE #52: Implement a "file picker" for the script path in run configuration
*Script path* in a run configuration has to be input manually, there is no file picker to chose from.

Other configurations  do have such a picker, e.g. goovy:
image

### LINKED ISSUE #129: Add support for Frosting
As in https://github.com/cake-build/cake-vs/issues/112, Rider should also support Cake.Frosting

### PR DESCRIPTION
**Pull request by js6pak**
Closes #129, closes #255, closes #52

- run configurations
image

- gutter icon
image

- tool window
image
(Special icons for cake script and cake frosting would be nice)

- [ ] snippets
- [x] convert cake script configuration editor to ControlViewBuilder

I took a very "do it as rider would" approach in this PR and ended up using a lot of rider types which changed quite a bit in rider 2022 (I suppose because of the unreal engine support) upping the version requirement.

### CODE REVIEW

**Comment by nils-a** [comment]
This looks brilliant, I need some time to process this. (Setting `pluginSinceBuild = 222` feels a bit of a hard cut - I need to chew on this.)

**Comment by js6pak** [comment]
> This looks brilliant, I need some time to process this. (Setting `pluginSinceBuild = 222` feels a bit of a hard cut - I need to chew on this.)

I have started working on this on 212, mostly namespaces changes so it would be trivial to port to another version, just not with the same .jar/.dll




> Does this also fix the inconsistency I observed in #255 ?
I have not looked into it yet, will do later

**Comment by js6pak** [comment]
> Does this also fix the inconsistency I observed in https://github.com/cake-build/cake-rider/pull/255 ?

I don't have a windows machine to test with atm but it should now be fixed with [this](https://github.com/cake-build/cake-rider/pull/260/files#diff-0366dc61e6cd13983db1b5abee0251a11b238fdb5eb4ec61a22cb654a10c8d3dR39)

@nils-a What snippets would be needed? Just task/async task? Also is it possible to enable live templates only on a frosting project?

**Comment by nils-a** [comment]
I tested your code before the last commit you made. Will test again tomorrow. Looks really cool so far.

One addition: If I open up a single frosting project (without a containing solution) the project picker in the run configuration does not list the project to be built.

> What snippets would be needed? Just task/async task?

Since we have no snippets in the other IDEs to copy from, yes - let's go with that and see if more is needed.

> Also is it possible to enable live templates only on a frosting project?

Not sure. I'd need to investigate.
I guess I would be possible to add another `TemplateContext` like
https://github.com/cake-build/cake-rider/blob/aa0cdc69d9d3965c5406b35923de3f71c4b0700d/src/rider/src/main/kotlin/net/cakebuild/liveTemplates/CakeContext.kt#L8-L13

and check for projects of type frosting and `.cs`..

Also, I'm not sure why the build currently fails - something with *GitVersion* being unable to calculate a nice version number for this PR. (Probably because I merged `master` into `develop` after screwing up the build 🙄)

**Comment by js6pak** [comment]
> One addition: If I open up a single frosting project (without a containing solution) the project picker in the run configuration does not list the project to be built.

Maybe it got fixed in the latest commit, but works fine for me?
image

**Review by nils-a — APPROVED** [review]
LGTM!

**Comment by nils-a** [comment]
@js6pak your changes have been merged, thanks for your contribution :+1:

I took the liberty to fix the linting problems in kotlin and also changed some styling in c#. Hope you don't mind.
I also added an `.editorconfig` to the c# project - so future styling should be easier 😁

**Pull request merged**
