### PR TITLE
Implement a file picker for the script path in run configuration

### LINKED ISSUE #52: Implement a "file picker" for the script path in run configuration
*Script path* in a run configuration has to be input manually, there is no file picker to chose from.

Other configurations  do have such a picker, e.g. goovy:
image

### PR DESCRIPTION
**Pull request by js6pak**
Closes #52

image

### CODE REVIEW

**Comment by js6pak** [comment]
The always failing appveyor is a bit annoying if you ask me

**Comment by nils-a** [comment]
> The always failing appveyor is a bit annoying if you ask me

Yea, you're right. Need to work on that. Seems it did not pain me enough. 🙄 

Thanks for getting the picker working - that's really cool. I'll have a look at it during the weekend and add that to the coming release.

**Comment by nils-a** [comment]
@js6pak does this store the relative path of the selected file or the absolute path? The image looks like it uses the absolute path. To be able to share the configurations between project members, that would need to be a relative path, I guess.

**Comment by js6pak** [comment]
Looks like intellij already handles it properly
image

**Comment by nils-a** [comment]
@js6pak This is kind of strange: While it works as expected on linux, on windows the path is stored absolute.

**Comment by js6pak** [comment]
I based it of groovy intellij plugin, can you check if you can reproduce that behaviour with a groovy run configuration?

**Comment by nils-a** [comment]
works as expected. However, groovy is only available in IDEA, so it might be RIDER "feature"?!

**Comment by nils-a** [comment]
superseeded by #260

**Pull request closed without merging**
